---
# 1
- name: "Add user: {{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    group: "{{ username }}"

# 2, 3
- name: Download and Unarchive
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /home/tgsl/
    remote_src: true
    # This is simpler 1 step solution to download and unarchive but it does not support checksum validation like uri module would
    # Ideally if not pulling/proxying from artifactory you would need to verify the checksum
  remote_user: tgsl # So we would not need to chmod later on

# 4
- name: Copy shell script
  ansible.builtin.copy:
    src: hello_world.sh
    dest: "/home/{{ username }}/{{ appname }}.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'  # This ensures that the script is executable

- name: Start the application script in the background
  # With nohup and 'fun' shell redirections we ensure that when ssh connection exits when ansible stops running
  # That it will not stop our background process script
  ansible.builtin.shell: nohup bash /home/{{ username }}/hello_world.sh > /dev/null 2>&1 &
  args:
    chdir: "/home/{{ username }}"
  changed_when: false
